CREATE TABLE account_profile
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    accountHolderName      VARCHAR (255),
    accountHolderSurname   VARCHAR (255),
    httpImageLink          VARCHAR (255),
    
    PRIMARY KEY (id)
);